/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface CardDealerInterface extends ethers.utils.Interface {
  functions: {
    "cards(uint32)": FunctionFragment;
    "createDeck()": FunctionFragment;
    "dealCard(uint32)": FunctionFragment;
    "deckOwners(address,uint256)": FunctionFragment;
    "decks(uint32)": FunctionFragment;
    "getCard(address,uint256)": FunctionFragment;
    "getCountByAddress(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "remaining(uint32)": FunctionFragment;
    "remainingIndices(uint32,uint256)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "cards", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "createDeck",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dealCard",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deckOwners",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "decks", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "getCard",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCountByAddress",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "remaining",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "remainingIndices",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "cards", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createDeck", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "dealCard", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deckOwners", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "decks", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getCard", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCountByAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "remaining", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "remainingIndices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "Card(address,string,uint32,uint32,uint32)": EventFragment;
    "Deck(address,uint32)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Card"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Deck"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export type CardEvent = TypedEvent<
  [string, string, number, number, number] & {
    owner: string;
    title: string;
    index: number;
    draw: number;
    deck: number;
  }
>;

export type DeckEvent = TypedEvent<
  [string, number] & { owner: string; deckId: number }
>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export class CardDealer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: CardDealerInterface;

  functions: {
    cards(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    createDeck(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    dealCard(
      deckId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deckOwners(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number]>;

    decks(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    getCard(
      owner: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [number, number, string] & { card: number; deckId: number; title: string }
    >;

    getCountByAddress(
      owner: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { count: BigNumber }>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    remaining(
      deckId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { count: BigNumber }>;

    remainingIndices(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  cards(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  createDeck(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  dealCard(
    deckId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deckOwners(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<number>;

  decks(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  getCard(
    owner: string,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [number, number, string] & { card: number; deckId: number; title: string }
  >;

  getCountByAddress(
    owner: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  remaining(
    deckId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  remainingIndices(
    arg0: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<number>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    cards(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    createDeck(overrides?: CallOverrides): Promise<number>;

    dealCard(deckId: BigNumberish, overrides?: CallOverrides): Promise<string>;

    deckOwners(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number>;

    decks(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    getCard(
      owner: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [number, number, string] & { card: number; deckId: number; title: string }
    >;

    getCountByAddress(
      owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    remaining(
      deckId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    remainingIndices(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Card(address,string,uint32,uint32,uint32)"(
      owner?: null,
      title?: null,
      index?: null,
      draw?: null,
      deck?: null
    ): TypedEventFilter<
      [string, string, number, number, number],
      {
        owner: string;
        title: string;
        index: number;
        draw: number;
        deck: number;
      }
    >;

    Card(
      owner?: null,
      title?: null,
      index?: null,
      draw?: null,
      deck?: null
    ): TypedEventFilter<
      [string, string, number, number, number],
      {
        owner: string;
        title: string;
        index: number;
        draw: number;
        deck: number;
      }
    >;

    "Deck(address,uint32)"(
      owner?: null,
      deckId?: null
    ): TypedEventFilter<[string, number], { owner: string; deckId: number }>;

    Deck(
      owner?: null,
      deckId?: null
    ): TypedEventFilter<[string, number], { owner: string; deckId: number }>;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;
  };

  estimateGas: {
    cards(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    createDeck(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    dealCard(
      deckId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deckOwners(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    decks(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    getCard(
      owner: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCountByAddress(
      owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    remaining(
      deckId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    remainingIndices(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    cards(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createDeck(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    dealCard(
      deckId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deckOwners(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    decks(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCard(
      owner: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCountByAddress(
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    remaining(
      deckId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    remainingIndices(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
