/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ArtProps, GalleryDeployment } from './types';

export const galleries: GalleryDeployment[] = [
	{
	  imageCid: 'bafybeiaqjcc6qrnvnwxsnc3m5uotquyk6wkzzowuvxa52frhijixeloqbe',
	  metadataCid: 'bafybeiazjlqz2z7lx2lluhreuujgxv3hou7z2gowcn4omypja6w4zjl5bi',
	  pieces: [
			{
				"src": "/art/bee-s-e120.jpg",
				"title": "Neon Bee",
				"artist": "0xBigBee",
				"media": "virtual neon",
				"contract": "0xBigBee"
			},
			{
				"src": "/art/bee-fancy-wing-0001-scientific-010.jpg",
				"title": "Bee Science Priestess",
				"artist": "0xBigBee",
				"media": "virtual pen"
			},
			{
				"src": "/art/bee-line-a60.jpg",
				"title": "Bee Study",
				"artist": "0xBigBee",
				"media": "ink"
			},
			{
				"src": "/art/bee-line-f40.jpg",
				"title": "Inked Bee Study #2",
				"artist": "0xBigBee",
				"media": "ink"
			},
			{
				"src": "/art/bee-gold-animation.gif",
				"title": "Golden Bee Animation",
				"artist": "0xBigBee",
				"media": "mixed digital"
			},
			{
				"src": "/art/small-red-bee.jpg",
				"title": "Red Bee",
				"artist": "0xBigBee",
				"media": "mixed digital"
			},
			{
				"src": "/art/magic-cat-ink.gif",
				"title": "Magic the Cat",
				"artist": "0xBigBee",
				"media": "ink"
			},
			{
				"src": "/art/eye-swarm.jpg",
				"title": "Eye Swarm",
				"artist": "0xBigBee",
				"media": "mixed digital"
			}
		],
	}
];
